import Head from 'next/head'
import CTA from '../components/CTA'
import Hero from '../components/Hero'
import Menu from '../components/Menu'
import Aboutus from '../components/Aboutus'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials'
import Team from '../components/Team'
import Blog from '../components/Blog'
import Faqs from '../components/Faqs'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Nellys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
       <Hero />
       <Menu />
       <CTA />
       <Aboutus />
       <Services />
       <Testimonials />
       <Team />
       <Blog />
       <Faqs />
       <Footer />
    </div>
  )
}
